language: android

branches:
  only:
    - master
    - develop
    - feature/types_to_int

android:
  components:
   - tools
   - platform-tools
   - build-tools-24.0.1
   - android-24
   - extra-android-m2repository

script:
  - ./gradlew :retroauth-core:build :retroauth-android:build

before_script:
  - echo "include ':retroauth-core', ':retroauth-android'" > settings.gradle

after_failure:
  - "cat /home/travis/build/andretietz/retroauth/retroauth-core/build/reports/tests/index.html"
  - "cat /home/travis/build/andretietz/retroauth/retroauth-android/build/reports/tests/index.html"
  - "cat /home/travis/build/andretietz/retroauth/retroauth-core/build/outputs/lint-results-debug.xml"
  - "cat /home/travis/build/andretietz/retroauth/retroauth-android/build/outputs/lint-results-debug.xml"